### ISSUE TITLE
Help needed!

### ISSUE THREAD

**Issue by CodePeacock** [AlphaArtrem/attendance_app#1]
I would like your help in activating your application for real.
It would mean the world to me.

**Comment by AlphaArtrem** [comment]
This is on a very old version of flutter and needs to be updated before making any changes.

**Comment by CodePeacock** [comment]
> This is on a very old version of flutter and needs to be updated before making any changes.

Yes @AlphaArtrem  you're right

And I would like your help to do that.

**Comment by CodePeacock** [comment]
Is there any way we could get in contact?

**Comment by CodePeacock** [comment]
Let me just say

**You made a mighty good app.**

**Comment by CodePeacock** [comment]
If you do think of updating this application please send me a email on fighterapache101@gmail.com

**Comment by CodePeacock** [comment]
Alright bye bro 🤪
